Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      # Health
      get 'health', to: 'health#show'

      # Signals — generated by Strategy Engine
      get  'signals',      to: 'signals#index'
      post 'signals/run',  to: 'signals#run'

      # Portfolio
      get  'portfolio/summary',    to: 'portfolio#summary'
      get  'portfolio/positions',  to: 'portfolio#positions'
      get  'portfolio/weights',    to: 'portfolio#weights'
      get  'portfolio/cashflows',  to: 'portfolio#cashflows'
      post 'portfolio/rebalance',  to: 'portfolio#rebalance'

      # Risk
      get  'risk/summary',    to: 'risk#summary'
      post 'risk/evaluate',   to: 'risk#evaluate'

      # Execution (proxies to paper_engine or live broker via ExecutionGateway)
      post 'orders',         to: 'orders#create'
      get  'orders',         to: 'orders#index'
      get  'orders/:id',     to: 'orders#show'
      delete 'orders/:id',   to: 'orders#destroy'

      # Instruments
      resources :instruments, only: [:index, :show]

      # Runtime Configs
      resources :runtime_configs, only: [:index, :show, :create, :update]

      # Strategies
      resources :strategies, only: [:index, :show]
    end
  end

  get 'up', to: 'rails/health#show', as: :rails_health_check
end
