require 'rails_helper'

RSpec.describe "Portfolio Intelligence (Phase 10)", type: :model do
  describe "Full Pipeline" do
    it "takes signals, optimizes weights, allocates capital, and constructs orders" do
      # 1. Signals generated by Strategy Engine (Phase 9)
      signals = [
        Strategy::Signal.new(instrument_id: 'RELIANCE', direction: 1, confidence: 0.8, strategy_name: 'Momentum'),
        Strategy::Signal.new(instrument_id: 'INFY', direction: 1, confidence: 0.2, strategy_name: 'Value')
      ]
      
      # 2. Portfolio Mandate
      mandate = Portfolio::Mandate.new(max_weight_per_asset: 0.50, min_cash_buffer_pct: 0.05)
      
      # 3. Optimizer evaluates target weights
      target_weights = Portfolio::Optimizer.optimize(signals, {}, mandate)
      
      # RELIANCE confidence is 0.8 / 1.0 = 0.80. Capped at max_weight 0.50.
      # INFY confidence is 0.2 / 1.0 = 0.20. 
      # Total sum = 0.70 (<= 0.95 max investable), so it stays.
      expect(target_weights['RELIANCE']).to eq(0.50)
      expect(target_weights['INFY']).to eq(0.20)
      
      # 4. Capital Allocation computes target absolute positions
      total_capital = 1_000_000
      current_prices = { 'RELIANCE' => 2500, 'INFY' => 1000 }
      
      # Target values: REL: 500k, INFY: 200k
      # Target qtys: REL: 200, INFY: 200
      target_positions = Portfolio::CapitalAllocationEngine.allocate(target_weights, total_capital, current_prices)
      
      expect(target_positions['RELIANCE']).to eq(200)
      expect(target_positions['INFY']).to eq(200)
      
      # 5. Construction Engine compares with current holdings
      # Let's say we already hold 100 RELIANCE and 300 HDFCBANK (which has no target weight, meaning sell)
      current_positions = { 'RELIANCE' => 100, 'HDFCBANK' => 300 }
      
      orders = Portfolio::ConstructionEngine.generate_orders(target_positions, current_positions, mandate)
      
      # Should generate 1 sell (HDFCBANK 300) and 2 buys (RELIANCE 100, INFY 200)
      # Priority: Sells first
      expect(orders.length).to eq(3)
      
      first_order = orders[0]
      expect(first_order[:side]).to eq('sell')
      expect(first_order[:instrument_id]).to eq('HDFCBANK')
      expect(first_order[:qty]).to eq(300)
      
      buys = orders[1..2]
      expect(buys.map { |o| o[:instrument_id] }).to match_array(['RELIANCE', 'INFY'])
      
      reliance_buy = buys.find { |o| o[:instrument_id] == 'RELIANCE' }
      expect(reliance_buy[:qty]).to eq(100) # 200 target - 100 current
      
      infy_buy = buys.find { |o| o[:instrument_id] == 'INFY' }
      expect(infy_buy[:qty]).to eq(200) # 200 target - 0 current
    end
  end
end
